# Generated by Django 4.0.1 on 2022-02-20 21:18

from django.db import migrations


def apply_migration(apps, *args, **kwargs):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('accounts', 'Profile')

    users = User.objects.filter(profile__isnull=True)
    for user in users:
        Profile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(apply_migration, migrations.RunPython.noop)
    ]
