# Generated by Django 4.0.1 on 2022-01-20 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_task_type_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Заголовок'),
        ),
    ]
