# Generated by Django 4.0.1 on 2022-01-24 06:25

from django.db import migrations, models
import webapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_task_description_alter_task_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, validators=[webapp.validators.MaxLengthValidator(2000)], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=255, validators=[webapp.validators.MinLengthValidator(2)], verbose_name='Заголовок'),
        ),
    ]
