# Generated by Django 4.0.1 on 2022-02-17 03:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0010_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ManyToManyField(default=1, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
