# Generated by Django 4.0.1 on 2022-02-17 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_project_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='users',
        ),
    ]
