# Generated by Django 4.0.1 on 2022-02-23 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_rename_user_project_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('change_user_in_own_project', 'Изменять список пользователей в своем проекте'),), 'verbose_name': 'проект', 'verbose_name_plural': 'проекты'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': (('add_task_in_own_project', 'Добавлять задачи в свой проект'), ('change_task_in_own_project', 'Редактировать задачи в своем проекте'), ('delete_task_in_own_project', 'Удалять задачи в своем проекте')), 'verbose_name': 'задача', 'verbose_name_plural': 'задачи'},
        ),
    ]
